### PR TITLE
Add treon tests

### LINKED ISSUE #7: Add test suite (treon via GitHub Actions)
I believe this repository would benefit from having a test suite that evaluates each notebook using [treon](https://github.com/ReviewNB/treon) to check for any errors.  Running this periodically would allow us to ensure that the code provided in these demos continues to work in future versions of Qiskit.

### PR DESCRIPTION
**Pull request by garrison**
Fixes #7

### Comments

I thought that opening this PR would trigger the new workflow, but it has not.  I believe this is because I am not an admin in this repo; I'm not sure if there's a way for an admin to easily approve it.  This PR's status does not indicate to me that any workflows are requiring approval, as I would expect from [GitHub Actions' docs](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks).

Fom my experience running this locally, I expect a few test failures, e.g. because the IBMQ account is not configured.  So I'll have to figure out how to handle these expected "failures." (EDIT: Done.)

As an alternative to calling treon directly, I could introduce a `tox.ini`, and then people could easily use tox to do the treon tests locally as well.  (EDIT: Done.)  This might be preferred, but I decided to keep this first draft simple.

### CODE REVIEW

**Comment by garrison** [comment]
Thinking more, I at first wanted to keep this change lightweight, but I am leaning now toward using `tox.ini`, so that people can easily test locally.

**Comment by garrison** [comment]
@HuangJunye This PR is now ready for review.  I expect that CI will pass, but I have no way of testing it myself.

I've added `tox.ini`, and the notebooks can be tested locally with `tox -epy39`.

I've made it so the notebooks will run (and tests will pass) whether or not an IBMQ account is available.

Other than that, the only fix required for the notebooks to run is that `LogNormalDistribution` has moved.

**Comment by HuangJunye** [comment]
@garrison Thanks a lot for working on this! Adding `tox.ini` is very useful and I could verify that all tests are passing.

@IceKhan13 Can you please have a look at this PR because I have no experience with GitHub workflow

**Review by IceKhan13 — APPROVED** [review]
LGTM!

Only 2 notes: 
- we probably want to start supporting `3.10` at some point in tests
- specifying dependencies without version is good as it will automatically pull latest versions, so we will know if anything will break

**Comment by HuangJunye** [comment]
Workflow is triggered! https://github.com/qiskit-community/qiskit-application-modules-demo-sessions/actions/runs/2220760757

**Comment by HuangJunye** [comment]
The test failed on Windows because pyscf is not on windows. Can we exclude testing of the nature notebook on windows? https://github.com/qiskit-community/qiskit-application-modules-demo-sessions/runs/6159142516?check_suite_focus=true

**Comment by garrison** [comment]
> The test failed on Windows because pyscf is not on windows. Can we exclude testing of the nature notebook on windows? 

sure :)

> we probably want to start supporting 3.10 at some point in tests

pyscf is not available yet in python 3.10, either, which is why I removed it from the workflow.

**Pull request merged**
